#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1"
# 
# if [[ "$1" = 0 ]]; then
#   if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
#     bspc monitor "$EXTERNAL_MONITOR" -d 7
#     bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6
#     bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
#   else
#     bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7
#   fi
# fi

# workspaces
bspc monitor primary -d 1 2 3 4 5 6 
bspc monitor HDMI-1 -d 7  # TODO: multiple monitors

bspc config focus_follows_pointer true

# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 17

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating
# bspc rule -a firefox state=floating
# bspc rule -a firefox desktop='^2' follow=on

# start resources
xrdb merge ~/.Xresources

# python script to always initialize with a different wallpaper:
# TODO: Add loading of basic scripts
#~/.config/bspwm/scripts/launch.sh &
feh --bg-scale ~/Images/wallpaperbetter.jpeg &
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
pkill battery-alert; ~/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/1.conf &

# autostart
flameshot &

